language: python
python:
  - "3.6"

cache:
  directories:
    - $HOME/.pip-cache/
    
# ignore the virtualenv that Travis creates
# setup a secure login to CodeCov
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - secure: 2c0250fb-dfb1-45c9-abaf-cd3d874326c5
# install mdl for checking Markdown
before_install:
  - gem install mdl
notifications:
  email: never

install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pipenv install --dev
  
script:
  - pipenv run pytest tests --cov-config pytest.cov --cov
  - pipenv run flake8 tests*
  - pipenv run pylint tests
  - mdl README.md

after_success:
  - pipenv run codecov

