language: python
python:
  - "3.5"

cache:
  directories:
    - $HOME/.pip-cache/
# install mdl for checking Markdown
before_install:
  - gem install mdl
notifications:
  email: never

install:
  - pip install --upgrade pip
  - python3 -m pip install -r requirements.txt
  - pip3 install pytest-flake8
  - pip3 install pytest-cov
  - pip3 install autopep8
  - python3 -m pip install --user gspread oauth2client
script:
  - pytest /tests/test_gatorgrouper.py
  - mdl README.md
  - coverage run --source tests -m py.test 
  - coverage report 

after_success:
  coveralls

